Document: acpi-backlightd
Title: Debian acpi-backlightd Manual
Author: <insert document author here>
Abstract: This manual describes what acpi-backlightd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/acpi-backlightd/acpi-backlightd.sgml.gz

Format: postscript
Files: /usr/share/doc/acpi-backlightd/acpi-backlightd.ps.gz

Format: text
Files: /usr/share/doc/acpi-backlightd/acpi-backlightd.text.gz

Format: HTML
Index: /usr/share/doc/acpi-backlightd/html/index.html
Files: /usr/share/doc/acpi-backlightd/html/*.html
